### ISSUE TITLE
Add support for machines that doesn't require encryption

### ISSUE THREAD

**Issue by d3m3trius** [ofalvai/home-assistant-candy#1]
On some machines, encryption is not used. With "encrypted=0" in the request you directly get the json in plain text.

Please, add support for these devices that doesn't require encryption.

**Comment by ofalvai** [comment]
I'm curious, does your machine work with `encrypted=1` too? Because my machine accepts `ecrypted=0`, but it also works with an encryption key, and it's easy to get the key using https://github.com/MelvinGr/CandySimplyFi-tool

Not saying I won't make it optional to use encryption, but currently it uses the key to make it compatible with both encrypted and non-encrypted devices.

**Comment by ofalvai** [comment]
I made encryption key optional in https://github.com/ofalvai/home-assistant-candy/commit/b2fa7c427bfa7e79b70b8997b6782a47d91f491e. You can update via HACS to the latest version. After a restart, you'll need to re-add the integration and on the config page you can uncheck the "Use encryption key" checkbox.

**Comment by NoNaMoe** [comment]
Hi, i think i found a quirk regarding this.
I have a Hoover washer dryer that uses this api and doesnt require encryption key, however...

http://x.x.x.x/http-read.json?encrypted=1 returns 7B0D0A09227374617475734C6176617472696365223A7B....
http://x.x.x.x/http-read.json?encrypted=0 returns {"response":"BAD REQUEST"}
http://x.x.x.x/http-read.json returns the last used encrypted option

Using 0.2.0, i get error with the integration:
Error communicating with API: Exception('Unable to detect machine type from API response', {'response': 'BAD REQUEST'})

Just for testing I changed this line in candy\client\__init__.py:
url = f"http://{self.device_ip}/http-read.json?encrypted={1 if self.use_encryption else 0}"
to not use the encrypted variable at all.

I no longer get the exception above, but i have a new error do do with parsing JSON which is a seperate issue (washer dryer not supported yet).

**Comment by ofalvai** [comment]
Yes, please open a new issue. This will require a bit more investigation, and others will find the ticket easier with a more relevant title.

I'm not sure how to overcome this behavior, because we can't detect the kind of response from the response alone, and I don't see any API endpoint that would reveal the exact model of the machine.
